### ISSUE TITLE
Add the possibility to add a 'media' folder containing graphics for the theme.

### ISSUE THREAD

**Issue by QazCetelic** [revoltchat/themes#24]
I use a few background images ([copyleft-license](https://pixabay.com/service/license/)). However, it currently requires hot-linking to an external third party service.
Adding a possibility to ship the graphics with the theme itself could solve this.

**Comment by brecert** [comment]
It's not ideal, however you *can* embed images within the css itself using [Data URIs](https://css-tricks.com/data-uris/).

**Comment by QazCetelic** [comment]
> It's not ideal, however you _can_ embed images within the css itself using [Data URIs](https://css-tricks.com/data-uris/).

I have ended up uploading it to Revolt and then using the image link to prevent the CSS file from becoming 100KB+.

**Comment by Rexogamer** [comment]
Files/media should be uploaded to Revolt, then linked to by the CSS - aside from anything, this prevents any CORS issues.
