### ISSUE TITLE
Add version to theme information

### ISSUE THREAD

**Issue by brecert** [revoltchat/themes#3]
A way to determine when a theme was changed would be good for tooling that uses themes, such as the theme shop for determining if the theme is outdated or different without deep checking the contents.

```
# URL friendly name
slug = "my-theme"

# Display name
name = "My Theme"

# Authors' name
creator = "An Individual"

# The commit this preset was built against
# Should only be specified if you use custom CSS that tends to break between updates
commit = "eea13a3"

# Preset description
description = "neat"

# The version of the theme
version = "1.2.3"
```

**Comment by Rexogamer** [comment]
This has since been added; however, not all themes have version numbers yet
